cmakemake: use official android.toolchain.cmake from NDK r13

diff --git a/cmake/cmakemake b/cmake/cmakemake
--- a/cmake/cmakemake
+++ b/cmake/cmakemake
@@ -190,7 +190,6 @@ if [ -n "$PLATFORM" ]; then
 
         for arch in $ARCHS; do
             BUILD_DIR="build/android/$BUILD_TYPE-$arch"
-
             mkdir -p "$BUILD_DIR"
             cd "$BUILD_DIR"
 
@@ -202,10 +201,17 @@ if [ -n "$PLATFORM" ]; then
             done
 
             NDK_DIR=`dirname "$NDK_FILENAME"`
-            TOOLCHAIN_FILE="$CMAKE_DIR/toolchain/android.toolchain.cmake"
+            if [ -d "$NDK_DIR/../prebuilt" ]; then
+                NDK_DIR="$NDK_DIR/.."
+            fi
+
+            TOOLCHAIN_FILE="$NDK_DIR/build/cmake/android.toolchain.cmake"
+            if [ ! -f "$TOOLCHAIN_FILE" ]; then
+                echo "ERROR: Unable to find '$TOOLCHAIN_FILE'. Make sure Android NDK r13 or newer is installed." >&2
+                exit 1
+            fi
 
             set --
-
             if [ "$OSTYPE" = "msys" ]; then
                 if [ -d "$NDK_DIR/prebuilt/windows-x86_64/bin" ]; then
                     MAKE_DIR="$NDK_DIR/prebuilt/windows-x86_64/bin"
@@ -223,8 +229,9 @@ if [ -n "$PLATFORM" ]; then
             fi
 
             set -- -DCMAKE_TOOLCHAIN_FILE="$TOOLCHAIN_FILE" "$@"
-            set -- -DANDROID_NDK="$NDK_DIR" -DANDROID_ABI="$arch" "$@"
-            set -- -DANDROID_NATIVE_API_LEVEL="android-9" -DANDROID_STL="stlport_shared" "$@"
+            set -- -DANDROID_ABI="$arch" "$@"
+            set -- -DANDROID_PLATFORM="android-9" "$@"
+            set -- -DANDROID_STL="stlport_shared" "$@"
 
             cmake "$@" $CMAKE_ARGS ../../..
 
