cmakemake: try default locations for NDK_DIR on macOS and Windows

diff --git a/cmake/cmakemake b/cmake/cmakemake
--- a/cmake/cmakemake
+++ b/cmake/cmakemake
@@ -179,19 +179,15 @@ if [ -n "$PLATFORM" ]; then
         done
         ;;
     android)
-        if ! which ndk-build > /dev/null 2>&1; then
-            echo "ERROR: Unable to find 'ndk-build'. Make sure Android NDK is installed and added to PATH." >&2
-            exit 1
-        fi
-
-        if [ -z "$ARCHS" ]; then
-            ARCHS="armeabi-v7a x86"
-        fi
-
-        for arch in $ARCHS; do
-            BUILD_DIR="build/android/$BUILD_TYPE-$arch"
-            mkdir -p "$BUILD_DIR"
-            cd "$BUILD_DIR"
+        if [ -f "$LOCALAPPDATA/Android/sdk/ndk-bundle/ndk-build.cmd" ]; then
+            NDK_DIR="$LOCALAPPDATA/Android/sdk/ndk-bundle"
+        elif [ -f "$HOME/Library/Android/sdk/ndk-bundle/ndk-build" ]; then
+            NDK_DIR="$HOME/Library/Android/sdk/ndk-bundle"
+        else
+            if ! which ndk-build > /dev/null 2>&1; then
+                echo "ERROR: Unable to find 'ndk-build'. Make sure Android NDK is installed and added to PATH." >&2
+                exit 1
+            fi
 
             NDK_FILENAME=`which ndk-build`
             while [ -h "$NDK_FILENAME" ]; do # resolve $NDK_FILENAME until the file is no longer a symlink
@@ -204,12 +200,22 @@ if [ -n "$PLATFORM" ]; then
             if [ -d "$NDK_DIR/../prebuilt" ]; then
                 NDK_DIR="$NDK_DIR/.."
             fi
+        fi
 
-            TOOLCHAIN_FILE="$NDK_DIR/build/cmake/android.toolchain.cmake"
-            if [ ! -f "$TOOLCHAIN_FILE" ]; then
-                echo "ERROR: Unable to find '$TOOLCHAIN_FILE'. Make sure Android NDK r13 or newer is installed." >&2
-                exit 1
-            fi
+        TOOLCHAIN_FILE="$NDK_DIR/build/cmake/android.toolchain.cmake"
+        if [ ! -f "$TOOLCHAIN_FILE" ]; then
+             echo "ERROR: Unable to find '$TOOLCHAIN_FILE'. Make sure Android NDK r13 or newer is installed." >&2
+             exit 1
+        fi
+
+        if [ -z "$ARCHS" ]; then
+            ARCHS="armeabi-v7a x86"
+        fi
+
+        for arch in $ARCHS; do
+            BUILD_DIR="build/android/$BUILD_TYPE-$arch"
+            mkdir -p "$BUILD_DIR"
+            cd "$BUILD_DIR"
 
             set --
             if [ "$OSTYPE" = "msys" ]; then
